### ISSUE TITLE
Is this project supported?

### ISSUE THREAD

**Issue by theodorosploumis** [dergachev/vagrant-drupal#7]
I am creating a list of **Drupal related vm and other tools**\* here http://goo.gl/ucwWdt .
Should I mark this project as obsolete?

Thanks.

**Comment by dergachev** [comment]
This is a Vagrant wrapper for the chef cookbook https://github.com/evolvingweb/chef-deploy-drupal
So it's fair to make it as obsolete.

FYI there's also https://github.com/evolvingweb/drupal-docker-marriage which isn't a framework but an example setup, which we are maintaining for the time being.

**Comment by theodorosploumis** [comment]
Thanks, I 've already seen this repo and will test it asap. The list is too large though and there are so many useful projects.

Anyway I am planning to create a series of blog posts about all these tools on Drupal planet.
Will let you know.
